/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f443d0b7d3f17d11542e390adff85f4c)
interface __BaseEnv_Env {
	FIREBASE_PROJECT_NUMBER: "365679413474";
	FIREBASE_ANDROID_APP_ID: "1:365679413474:android:5b19dac485b52fe1d2b6bb";
	FIREBASE_IOS_APP_ID: "1:365679413474:ios:241c176505a41fedd2b6bb";
	API_BIBLE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FIREBASE_PROJECT_NUMBER" | "FIREBASE_ANDROID_APP_ID" | "FIREBASE_IOS_APP_ID" | "API_BIBLE_KEY">> {}
}
