/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a0d9f9eaaa385f1ae2c3ed4c01ad3870)
interface __BaseEnv_Env {
	API_BIBLE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "API_BIBLE_KEY">> {}
}
