import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

Future<void> registerLicenses() async {
  LicenseRegistry.addLicense(() async* {
    yield LicenseEntryWithLineBreaks(['Bitter'], await rootBundle.loadString('fonts/Bitter-OFL.txt'));
    yield LicenseEntryWithLineBreaks(['Lora'], await rootBundle.loadString('fonts/Lora-OFL.txt'));
    yield LicenseEntryWithLineBreaks(['Merriweather'], await rootBundle.loadString('fonts/Merriweather-OFL.txt'));
    yield LicenseEntryWithLineBreaks(['PT Serif'], await rootBundle.loadString('fonts/PTSerif-OFL.txt'));
    yield LicenseEntryWithLineBreaks(['Open Sans'], await rootBundle.loadString('fonts/OpenSans-OFL.txt'));
    yield LicenseEntryWithLineBreaks(['Lato'], await rootBundle.loadString('fonts/Lato-OFL.txt'));
    yield LicenseEntryWithLineBreaks(['Libron'], await rootBundle.loadString('fonts/Libron-OFL.txt'));
    yield LicenseEntryWithLineBreaks(['OpenDyslexic'], await rootBundle.loadString('fonts/OpenDyslexic-OFL.txt'));
    yield LicenseEntryWithLineBreaks(['Ezra SIL'], await rootBundle.loadString('fonts/EzraSIL-OFL.txt'));

    yield const LicenseEntryWithLineBreaks(
      ['Berean Standard Bible (BSB)'],
      '''
The Holy Bible, Berean Standard Bible, BSB is produced in cooperation with Bible Hub, Discovery Bible, OpenBible.com, and the Berean Bible Translation Committee.

https://berean.bible/''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['King James Version (KJV)'],
      '''
The Holy Bible, King James Version (KJV), 1769.

The King James Version base text is in the public domain in the United States and most of the world. (In the United Kingdom, rights are vested in the Crown.)

Strong's numbers, Greek morphology, and footnotes are taken from the KJV SWORD module of the CrossWire Bible Society, licensed under the GNU General Public License (GPL). Hebrew morphology is derived from the Open Scriptures Hebrew Bible, licensed under Creative Commons Attribution 4.0 (CC BY 4.0).

Source: https://www.crosswire.org''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['King James Version (KJV) Audio Bible'],
      '''
Narration by David, retrieved from OpenBible.com.

Source: https://openbible.com/audio/kjv/''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Berean Standard Bible (BSB) Audio Bible'],
      '''
Narration by Barry Hays, retrieved from Berean Bible.

Source: https://berean.bible/''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Majority Standard Bible (MSB)'],
      '''
The Holy Bible, Majority Standard Bible, MSB is produced in cooperation with Bible Hub, Discovery Bible, OpenBible.com, and the Berean Bible Translation Committee. The text is dedicated to the public domain.

Text, paragraph formatting, and footnotes are taken from the USX edition generated by bsb2usfm, licensed under the MIT License.

Sources:
https://majoritybible.com/
https://github.com/BSB-publishing/bsb2usfm''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['American Standard Version (ASV)'],
      '''
The Holy Bible, American Standard Version (ASV), 1901.

The American Standard Version is in the public domain.

Text, paragraph formatting, and footnotes are taken from the ASV SWORD module distributed by the CrossWire Bible Society, sourced from eBible.org.

Source: http://www.ebible.org/bible/asv/''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['World English Bible (WEB)'],
      '''
The World English Bible is in the public domain. "World English Bible" is a trademark of eBible.org.

Text, paragraph formatting, and footnotes are taken unchanged from eBible.org's USFM edition, which omits the Deuterocanon.

Source: https://ebible.org/find/show.php?id=engwebp''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Byzantine Textform 2005 (BYZ)'],
      '''
The New Testament in the Original Greek: Byzantine Textform 2005, edited by Maurice A. Robinson and William G. Pierpont.

The editors released the Greek text into the public domain. It may be copied, distributed, stored in a database, incorporated into other works, and otherwise used without restriction. Attribution is retained to identify the edition and responsibility for the text. Lux's use does not imply the editors' or publisher's agreement with Lux's views.

Lux converts the official one-verse-per-line ASCII edition to unaccented lowercase Unicode Greek and its bundled Bible data format.

Sources:
https://byzantinetext.com/study/editions/robinson-pierpont/
https://www.dropbox.com/s/oil2m3la4vsnbpb/editions-rp2-ascii.zip?dl=0''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Statenvertaling (SV)'],
      '''
The Holy Bible, Statenvertaling, 1637.

The Statenvertaling is in the public domain.

Text obtained from the DutSVV SWORD module distributed by the CrossWire Bible Society. CrossWire's module is based on the electronic edition from Statenvertaling online. Lux transforms the module into its bundled Bible data format.

Sources:
https://www.crosswire.org/sword/modules/ModInfo.jsp?modName=DutSVV
https://bijbel.coas.nl/''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Petrus Canisiusvertaling 1939 (NLD1939)'],
      '''
De Heilige Schrift, Petrus Canisiusvertaling, 1939.

The Petrus Canisius translation is in the public domain.

Text obtained from the nld1939eb SWORD module published by eBible.org. Lux transforms the module into its bundled Bible data format and uses eBible.org's verse-marked HTML for Daniel because the module stores Daniel under the combined Catholic DAG book.

Source: https://ebible.org/bible/details.php?id=nld1939''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Unrevidierte Elberfelder 1905 (ELB1905)'],
      '''
Die Heilige Schrift, Unrevidierte Elberfelder Uebersetzung, 1905.

Public domain. Originally copyrighted by R. Brockhaus Verlag, Germany; the text has since passed into the public domain.

Text obtained from the GerElb1905 SWORD module distributed by the CrossWire Bible Society, whose text comes from the Unbound Bible. Lux transforms the module into its bundled Bible data format.

Source: https://www.crosswire.org/sword/modules/ModInfo.jsp?modName=GerElb1905''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Lutherbibel 1912 (LUT1912)'],
      '''
Die Bibel, Lutherbibel 1912, uebersetzt von Martin Luther.

Public domain. This work is not copyrighted and may be copied and published freely.

Text obtained from the deu1912eb SWORD module published by eBible.org. Lux transforms the module into its bundled Bible data format and keeps the module's German verse references in `origin` where Luther's versification differs from Lux's.

Source: https://ebible.org/find/details.php?id=deu1912''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['La Sainte Bible, Ostervald 1744 (FOB)'],
      '''
La Sainte Bible, Ostervald 1744.

Public domain. This work may be copied and published freely.

Text obtained from the fraFOB1744eb SWORD module distributed by eBible.org. Lux transforms the module into its bundled Bible data format.

Source: https://eBible.org/Scriptures/''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Bible David Martin 1744 (Martin)'],
      '''
La Sainte Bible, Version David Martin 1744.

Public domain.

Text obtained from the FreBDM1744 SWORD module distributed by the CrossWire Bible Society. Lux transforms the module into its bundled Bible data format.

Sources:
https://www.crosswire.org/sword/modules/ModInfo.jsp?modName=FreBDM1744
http://earnestlycontending.com/BibleMartin/index.html''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Santa Biblia Reina Valera Gómez 2010 (RVG)'],
      '''
Santa Biblia Reina Valera Gómez.

Copyright © 2004, 2010, 2023 Dr. Humberto Gómez Caballero. All rights reserved.

Free non-commercial distribution is permitted when the text is not changed. Printing or reproduction for profit is prohibited.

Text obtained from the sparvg2010eb SWORD module distributed by eBible.org. Lux transforms the module into its bundled Bible data format.

Source: https://eBible.org/Scriptures/''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Russian Synodal Bible 1876 (SYNO)'],
      '''
Библия. Синодальный перевод, 1876.

Public domain. Translated by the Orthodox theological academies of Moscow, Saint Petersburg, Kazan, and Kiev.

Text obtained from the RusSynodal SWORD module distributed by the CrossWire Bible Society. Lux transforms the module into its bundled Bible data format and keeps the module's Synodal verse references in `origin` where the Synodal versification differs from Lux's. The Synodal psalter follows the Greek numbering, so its psalms are regrouped onto their Hebrew numbers. The deuterocanonical books and passages the Synodal carries (Ps 151, the additions to Daniel, and the Septuagint pluses in Joshua, Proverbs, and Numbers) are not included.

Source: https://www.crosswire.org/sword/modules/ModInfo.jsp?modName=RusSynodal''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Tagalog Unlocked Literal Bible (ULB)'],
      '''
banal na Bibliya. Tagalog Unlocked Literal Bible.

Copyright © 2018 Door43 World Missions Community.

Translation by: Door43 World Missions Community

Contributors: Abantes, Glosamie R., Abluyan, Nieves, Aggasid, John Stephen, Aldana, Marvin J., Ancheta, Jonathan, Andaya, Reymond, Aril, Rene, Atienza, Melchizedek Eleazar, Atmagol, Efraim P., Auxillo, Alfredo S., Balbieran, Ruth M., Bibay, Roland Dave, Cadiente, Dandel, Ca s, Randy, Ca , Benedicto, Canonoy, Neil Ian P., Castelo, Kathleen, Castillo, Madeline, Chiong, Armie, Co, Corizin F., Covita, Mark, Delos Reyes, Rachel, Dingle, Buena Kathleen, Eloja, Nestor Raul P., Emboc, Tano, Eugenio, Alfred, Evangelista, Carmelita, Fajardo-Barcebal, Rosalle, Fianza, Arlyn, Flores, Christopher V., Flores, Rommel, Fradejas, Daniel G., Frias, Ronald, Galvez, Garry C., Gatchalian, James A., Gomez, Roniza May L., Inway, Jennilyn, Langres, Arsenio, Langres, Vicki M., Langres, Zimri, Lantion, Ralph, Lapira, Ronaldo Jr, C., Laya, Anita, Lazo, Jeffrey, Lopez, Josephine, Lorona, Marvina U., Mampo, Genelyn U., Mijares, Racquel, Monteverde, Julian Angelo, Morales, Gilbert, Oday, Gabriel, Ong, Reynante, Ordo Arsenio Jr., Osabel, Hesa Joyce, Pabellion-Lasinga, Beryl Joi, Palagimlan, Ray Mart E., Paller, Beth, Paller, Romy, Palomar, Carmina, Panes, Jona Mae K., Pawid, Jake, Pido, Miriam, Pin-ag, Rose Ann, Revilla Adelaido D. Jr, Reyes, Dominic, Riate, Erick Jan, Rivera, Diana, Salda Helen, Saptang, Bethlehem P., Sibayan, Mizpha, Talimodao, Sheldon Jay T., Tuang, Mandel John C., Umpatang, Jimmy, Vergara, Johanne G., Villorente, Dea Rose, Achacoso, Hamir Ibrahim, Adriano, Wilfredo R., AKI, Aril, Lala, Atienza, Melchizedek Eleazar, Auxillo, Alfredo S., Bagamaspao, Elison C., Balbieran, Romilyn, Balbieran, Ruth, Baldemor, Emily Mary Jane, Baldemor, Nathaniel, Bantique, Flor, Basto, Pacifico Jr., Bayang, Rochelle , Bernales, Vicente P., BJMP, Bubod, Fortunato M., Buzeta, Drake Nikko, Cabigting, Romeo, Cabrera, Teresita, Camandero, Vivian, Castillo, Madeline, Cuarto, Victor Immanuel, Depending2Christ1990, Eloja, Nestor Raul P., Emboc, Tano, Enojas, David James, Evangelista, Carmelita, Fianza, Arlyn, Gab, Galvez, Garry, Ganiban, Rafael, Gatchalian, James A., Glosa, Gumangan, Julius, Gutierrez, Robin Rhoy, Inway, Jennilyn, Jimenez, Alvin, Julito Opider, Lanira, Rolando U. Jr, Laya, Anita, Lopez, Josephine, Madawat, Glory, Mam, Geneohoy, Manaois, Charlie Jay, Mharus, Mijares, Racquel, Palagimlan, Rey Mart E., Palileo, Reynaldo Jr., Paller, Romy, Panes, Jona Mae K., Pangadlin, Jun, Paraiso, Lorelie Rachel, Pavin, Pawid, Jake, Peralta, Rodolfo, Perez, Ian Hudson, Phraim 91, Pin-ag, Rose Ann, Pobadora, Josephine M., Pura, Saniel, Ralph, Lantion, Rene Aril, Revilla, Adelaido Jr, Rull, Fernando, Rupa, Jonathan, Saptang, Bethlehem P., Selle, Serqui Bernard, Singgangan, Josie, Talimodao, Sheldon Jay T., Veloso, Alfonil, Veloso, Helen, Venus, Jorito, Vergara, Johanne G., Villorente, Dea Rose, Yosores, Momer B.

Licensed under Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0): https://creativecommons.org/licenses/by-sa/4.0/

Adapted from the tglulb2018eb SWORD module distributed by eBible.org. The original licensor does not necessarily endorse these changes. Lux transforms the module into its bundled Bible data format and keeps the module's NRSV verse references in `origin` where they differ from Lux's: 3 John 1:15 is combined with 3 John 1:14, and Revelation 12:18 with Revelation 13:1. Verses the translators merged into a neighboring verse, which the source leaves as a "-" placeholder (1 Chronicles 8:17, 19, 20, 22-24, and 26, and Daniel 4:28), and the repeated half of the Numbers 14:36-37 verse bridge are omitted. The adapted text is distributed under the same license.

Source: https://eBible.org/tglulb/''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Septuagint, Rahlfs (LXX)'],
      '''
Septuagint, Morphologically Tagged Rahlfs' text.

Copyrighted; free non-commercial distribution.

Text obtained from the LXX SWORD module distributed by the CrossWire Bible Society. The module was built from data from the Center for Computer Analysis of Texts at the University of Pennsylvania. Lux transforms the module into its bundled Bible data format.

Source: https://www.crosswire.org/sword/modules/ModInfo.jsp?modName=LXX''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Textus Receptus, Stephens 1550 (TR)'],
      '''
Textus Receptus, Stephens 1550, transcribed and proofed by Maurice A. Robinson. The source also records Scrivener 1894 variants.

The electronic Greek text was released into the public domain and may be used for any purpose. Attribution is retained to identify the preparer and responsibility for the text.

Lux converts the official ASCII source to unaccented lowercase Unicode Greek and its bundled Bible data format.

Sources:
https://byzantinetext.com/study/editions/scrivener/
https://www.dropbox.com/s/dnlsgrcan5t36sk/editions-stevens-scrivener-parsed.zip?dl=0''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Statistical Restoration Greek New Testament (SR)'],
      '''
Statistical Restoration Greek New Testament, edited by Alan Bunning, Center for New Testament Restoration.

Copyright © 2022-2023 Alan Bunning. Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0): https://creativecommons.org/licenses/by/4.0/

Lux transforms the source text into its bundled Bible data format.

Source: https://github.com/Center-for-New-Testament-Restoration/SR/blob/4be18e67c6870388d317d38d2b10a70e8b5e8775/SR.tsv''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Open Scriptures Hebrew Bible (OSHB)'],
      '''
Open Scriptures Hebrew Bible, based on the public-domain Westminster Leningrad Codex.

Licensed under Creative Commons Attribution 4.0 International (CC BY 4.0): https://creativecommons.org/licenses/by/4.0/

Original work of the Open Scriptures Hebrew Bible available at https://github.com/openscriptures/morphhb

Lux transforms the source text into its bundled Bible data format.

Source: https://github.com/openscriptures/morphhb''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Tyndale Open Study Notes'],
      '''
Tyndale Open Study Notes. Copyright © 2022 Tyndale House Publishers.

Licensed under Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0): https://creativecommons.org/licenses/by-sa/4.0/

Adapted from Tyndale Open Study Notes. The original work by Tyndale House Publishers is available for free at http://www.tyndaleopenresources.com.

Changes made by Lux: the study notes, book introductions, and book summaries were converted into Lux's bundled commentary format, with bullet-separated points split into paragraphs and each summary's title line removed. The people profiles and theme articles were converted into Lux's article format, with their title lines removed and each "Passages for Further Study" list turned into the article's linked passages alongside its main passage. Printed reference labels that repeat the section heading were removed, malformed scripture links were repaired, links to content not included in Lux were removed, and a few verse numbers were aligned with Lux's versification.

Source: http://www.tyndaleopenresources.com''',
    );

    yield const LicenseEntryWithLineBreaks(
      ["Matthew Henry's Commentary"],
      '''
Matthew Henry's Commentary on the Whole Bible.

Written by Matthew Henry (1662–1714); first published in 1706. The work is in the public domain.

Obtained from the Christian Classics Ethereal Library (CCEL). CCEL hosts editions based on books that are in the public domain in the United States, made available for personal, educational, or non-profit use.

Source: https://ccel.org/ccel/henry/mhc''',
    );

    yield const LicenseEntryWithLineBreaks(
      ["John Calvin's Commentaries"],
      '''
John Calvin's collected Bible commentaries.

The commentary is in the public domain. Lux's electronic text was obtained from the Christian Classics Ethereal Library (CCEL).

Sources:
https://www.ccel.org/ccel/calvin
https://crosswire.org/sword/modules/ModInfo.jsp?modName=CalvinCommentaries''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Jamieson-Fausset-Brown Commentary'],
      '''
Commentary Critical and Explanatory on the Whole Bible by Robert Jamieson, A. R. Fausset, and David Brown, first published in 1871.

The work is in the public domain. Lux's electronic text was obtained from the Christian Classics Ethereal Library (CCEL).

Source: https://www.ccel.org/ccel/jamieson/jfb.html''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Cross References'],
      '''
Cross-reference data.

Copyright © OpenBible.info. Licensed under a Creative Commons Attribution License (CC BY 4.0): https://creativecommons.org/licenses/by/4.0/

The dataset is derived from the Treasury of Scripture Knowledge (public domain), with supplementary data from OpenBible.info.

Source: https://www.openbible.info/labs/cross-references/''',
    );

    yield const LicenseEntryWithLineBreaks(
      ["Strong's Greek & Hebrew Dictionaries"],
      '''
Strong's Greek and Hebrew Dictionaries.

Dictionaries of Greek and Hebrew words taken from Strong's Exhaustive Concordance by James Strong, S.T.D., LL.D. (1890). Public Domain — Copy Freely.

Digital editions prepared and corrected by the OpenScriptures project (contributors include Ulrik Petersen, David Troidl, and David Instone-Brewer).

Source: https://github.com/openscriptures/strongs
  - greek/StrongsGreekDictionaryXML_1.4/strongsgreek.xml
  - hebrew/StrongHebrewG.xml

The public-domain status of the Greek dictionary is also documented by the CrossWire Bible Society:
https://www.crosswire.org/sword/modules/ModInfo.jsp?modName=StrongsGreek''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Tyndale Open Bible Dictionary'],
      '''
Tyndale Open Bible Dictionary. Copyright © 2023 Tyndale House Publishers.

Licensed under Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0): https://creativecommons.org/licenses/by-sa/4.0/

Adapted from Tyndale Open Bible Dictionary. The original work by Tyndale House Publishers is available for free at http://www.tyndaleopenresources.com.

Changes made by Lux: the dictionary articles were converted into Lux's article format, with their title lines removed, the asterisks that mark terms missing from the New Living Translation removed, and their text boxes and charts placed inline. Malformed scripture links were repaired, links to deuterocanonical books and to content not included in Lux were removed, and a few verse numbers were aligned with Lux's versification. The pictures were omitted because the open release does not include their images.

The maps were rasterized from their PDFs. Map entries that share an image were merged into one map, several titles were rewritten to describe what the map shows, captions that did not match their map or only repeated a reference printed on the map were removed, scripture references in captions were given their book names, typos in captions were corrected, and each map was linked to the passages it illustrates.

Source: http://www.tyndaleopenresources.com''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Creeds & Confessions'],
      '''
The creeds, confessions, and catechisms are historical documents in the public domain. Their electronic texts and Scripture proofs come from Creeds.json, released under the Unlicense.

Changes made by Lux: the Apostles' Creed uses its traditional English wording, as given in Philip Schaff's The Creeds of Christendom. Two Scripture proof references were corrected, three chapter titles of the 1689 London Baptist Confession were corrected, the Canons of Dort were numbered by head of doctrine with their rejections of errors listed separately, and stray formatting characters were removed. Documents whose texts are under copyright were not included.

Source: https://github.com/NonlinearFruit/Creeds.json''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['BibleProject Videos'],
      '''
BibleProject is the author and owner of this content. To find more BibleProject resources, visit bibleproject.com.

The videos are streamed from BibleProject and are not stored in Lux. Lux lists them with their titles and artwork unchanged and links each video to the passages it explains.

Source: https://bibleproject.com''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Bible Reading Plans'],
      '''
Reading plan schedules (daily passage references only; no Bible text is included).

Compiled from the open-source "readingplans" project by Kyle Hornberg, licensed under the MIT License, itself derived from devkardia/bibleplan.
https://github.com/khornberg/readingplans

The individual plans remain the work of their original publishers:

M'Cheyne — Robert Murray M'Cheyne (1813-1843). Public domain.

Old and New Testament; Gospels and Epistles; Every Day in the Word; Literary Study Bible; Chronicles and Prophets; Pentateuch and History of Israel; Psalms and Wisdom Literature: ESV reading plans, Crossway. https://www.esv.org

Through the Bible: Equipping Godly Women Bible in a Year Reading Plan. https://equippinggodlywomen.com/faith/read-the-bible-in-a-year/

One Year Chronological: The One Year Bible, Tyndale House Publishers. https://www.oneyearbibleonline.com

Historically Blended; Different Topics; New Testament, Psalms & Proverbs: Heartlight, Inc. https://www.heartlight.org

5x5x5 New Testament Bible Reading Plan: Copyright © 2005 by The Navigators. All Rights Reserved. Adapted from the Discipleship Journal 5x5x5 Bible Reading Plan. Permission is granted to reprint unlimited copies for non-commercial use. All copyright information must be retained. https://www.navigators.org/resource/bible-reading-plans/

Only the daily passage references are used; the Scripture text is provided under the Bible translation licenses.''',
    );

    yield const LicenseEntryWithLineBreaks(
      ['Verse of the Day', "Jonathan Bagster's Daily Light on the Daily Path"],
      '''
The Verse of the Day passage schedule is derived from Jonathan Bagster's Daily Light on the Daily Path: A Devotional Textbook for Every Day of the Year, in the Very Words of Scripture.

Prepared by Jonathan Bagster (1813-1872) and other members of his family. Distributed by the CrossWire Bible Society as the Daily SWORD module, version 1.0. Public domain. Copy freely.

Only the calendar schedule and Scripture references are included. Scripture text is provided under the selected Bible translation's license.

Source: https://www.crosswire.org/sword/modules/ModInfo.jsp?modName=Daily''',
    );
  });
}
