include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude: ["**.freezed.dart", "**.g.dart", "build/**", android/**, ios/**, web/**, windows/**, macos/**, linux/**]
  plugins:
    - custom_lint

linter:
  rules:
    always_use_package_imports: true
    sort_child_properties_last: false

formatter:
  page_width: 120
